[package]
name = "onedrive-api"
version = "0.1.0"
authors = ["uHOOCCOOHu <hooccooh1896@gmail.com>"]
repository = "https://github.com/uHOOCCOOHu/onedrive-api"
license = "MIT"
categories = ["api-bindings"]
keywords = ["onedrive", "http", "client", "api"]
description = "OneDrive REST API Client"

[dependencies]
reqwest = "^0.9"
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
url = "^1.7"
