[package]
name = "onedrive-api"
version = "0.4.0"
authors = ["oxalica <oxalicc@pm.me>"]
repository = "https://github.com/oxalica/onedrive-api"
license = "MIT"
categories = ["api-bindings"]
keywords = ["onedrive", "http", "client", "api"]
description = "OneDrive REST API Client"
edition = "2018"
readme = "README.md"
documentation = "https://docs.rs/onedrive-api"

[dependencies]
failure = { version = "0.1.6", features = ["derive"] }
lazy_static = "1.4.0"
reqwest = "0.9.22"
serde = { version = "1.0.102", features = ["derive"] }
serde_json = "1.0.41"
url = "1.7.2"

[dev-dependencies]
env_logger = "0.7.1"
log = "0.4.8"
rand = "0.7.2"
