[package]
name = "onedrive-api"
version = "0.1.0"
authors = ["uHOOCCOOHu <hooccooh1896@gmail.com>"]
repository = "https://github.com/uHOOCCOOHu/onedrive-api"
license = "MIT"
categories = ["api-bindings"]
keywords = ["onedrive", "http", "client", "api"]
description = "OneDrive REST API Client"
edition = "2018"

[dev-dependencies]
env_logger = "^0.6"
lazy_static = "^1.2"
log = "^0.4"

[dependencies]
reqwest = "^0.9"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
url = "^1.7"
