[package]
name = "onedrive-api"
version = "0.5.2"
authors = ["oxalica <oxalicc@pm.me>"]
repository = "https://github.com/oxalica/onedrive-api"
license = "MIT"
categories = ["api-bindings"]
keywords = ["onedrive", "http", "api"]
description = "OneDrive HTTP REST API"
edition = "2018"
readme = "README.md"
documentation = "https://docs.rs/onedrive-api"

[features]
default = []
beta = []

[dependencies]
bytes = "0.5.4"
reqwest = { version = "0.10.4", features = ["json"] }
serde = { version = "1.0.102", features = ["derive"] }
serde_json = "1.0.41"
strum = { version = "0.18.0", features = ["derive"] }
thiserror = "1.0.15"
url = "2.1.1"

[package.metadata.docs.rs]
all-features = true

[workspace]
members = ["onedrive-api-test"]
