[package]
name = "onedrive-api"
version = "0.5.2"
authors = ["oxalica <oxalicc@pm.me>"]
repository = "https://github.com/oxalica/onedrive-api"
license = "MIT"
categories = ["api-bindings"]
keywords = ["onedrive", "http", "api"]
description = "OneDrive HTTP REST API"
edition = "2018"
readme = "README.md"
documentation = "https://docs.rs/onedrive-api"

[features]
default = []

[dependencies]
failure = { version = "0.1.6", features = ["derive"] }
http = "0.2.1"
lazy_static = "1.4.0"
pico-args = "0.3.1"
reqwest = { version = "0.10.4", features = ["json"] }
serde = { version = "1.0.102", features = ["derive"] }
serde_json = "1.0.41"
url = "2.1.1"

[package.metadata.docs.rs]
features = []

[workspace]
members = ["onedrive-api-test"]
